# Generated by Django 4.2.4 on 2023-08-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Subscription',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subcribe_news',
            new_name='subscribe_news',
        ),
    ]
