# Generated by Django 4.2.4 on 2023-08-31 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0003_alter_subscription_email_alter_subscription_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
