# Generated by Django 4.2.4 on 2023-09-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0005_contactformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='category',
            field=models.CharField(choices=[('feedback', 'Feedback / Questions about our online courses'), ('speaking', 'Speaking engagement for Andrew Ng'), ('press', 'Press or interview request'), ('advice', 'Entrepreneurship or career advice'), ('other', 'Other')], max_length=20),
        ),
    ]
