# Generated by Django 4.2.4 on 2023-09-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0006_alter_contactformsubmission_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='category',
        ),
    ]
