# Generated by Django 4.2.4 on 2023-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_heading_article_subheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
