# Generated by Django 4.2.4 on 2023-09-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_heading_remove_article_subheading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading',
            name='article',
        ),
        migrations.RemoveField(
            model_name='subheading',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Heading',
        ),
        migrations.DeleteModel(
            name='Subheading',
        ),
    ]
