# Generated by Django 4.2.4 on 2023-09-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='publication_date',
        ),
    ]
