# Generated by Django 4.2.4 on 2023-09-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_modules_alter_module_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='modules',
        ),
    ]
