# Generated by Django 4.2.4 on 2023-09-02 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='image',
            field=models.ImageField(default="{ static 'img/default.jpg'}", upload_to='insight/img/'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
